default: &default
  site_name: "Sample App"
  admin_email: "admin@example.com"
  digit_10: 10

development:
  <<: *default

production:
  <<: *default
  site_name: "Sample App"

mailer:
  from: "noreply@example.com"
